### ISSUE TITLE
SSH bastion compatibility

### ISSUE THREAD

**Issue by snk33** [isontheline/pro.webssh.net#110]
Hello again :)

**Pseudo-terminal**

Some SSH bastion rely on ssh pseudo-terminal capabilities to work, which works on a unix terminal with this "ssh" option :
```
-t      Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.  Multiple -t options force tty allocation, even if ssh has no local tty.
```

We're implementing The Bastion from OVH (open-sourced recently) and it seems that we cannot make it work.

**Send command on ssh connection**

Also, it seems impossible to send command on ssh connection rather than the connected shell once loaded, using "launch command on connection". OVH dev has tested and replied :
```
ok, the "launch command on connection" is actually waiting for a bash prompt to manually input the command you have configured (as if you typed it on your keyboard), this is different from specifying a command directly on the ssh command-line, that's why you can't make it work.

Maybe the WebSSH dev could add the feature ;)
```

The command line equivalent would be :
```
ssh -i ~/.ssh/myprivatekey -t user@bastion -- COMMAND
```

Example of command in case of OVH The Bastion :
```
root@host
```

That will connect to the remote server via bastion.

I know this feature request is about specific use case but I hope SSH bastion will be more frequently used (thanks to open-source project like this one), security being a critical concern in the Internet jungle :)
And of course it'll be a good one for pro version.

Related issue on The Bastion project : https://github.com/ovh/the-bastion/issues/54

Have a good day !

**Comment by isontheline** [comment]
Re @snk33👋

Thank you a lot for this great issue!

I will check how I can improve pseudo terminal support inside WebSSH, asap

**Comment by snk33** [comment]
You’re welcome.

I hope it won’t be too much work to achieve this but it would be so nice to promote that kind of open-source solution (cocorico ^^).

**Comment by snk33** [comment]
To follow message on the-bastion issue, it seems that "-t" option is already used by default, at least now I can connect to the bastion and use it normally.

Only the send command on ssh connect part could be added then.

**Comment by isontheline** [comment]
I'm working on it right now. 

Getting some glitches but I'm confident 😇

**Comment by isontheline** [comment]
Hello @snk33 

After a lot of bad tries :
![Capture d’écran 2020-11-21 à 21 46 55](https://user-images.githubusercontent.com/44212923/99887261-2d566600-2c43-11eb-916e-a8fdc372daa2.png)

I'm now able to send commands :
![Capture d’écran 2020-11-21 à 21 49 24](https://user-images.githubusercontent.com/44212923/99887344-d56c2f00-2c43-11eb-82c3-9966a06267e2.png)

Even interactive mode :
![Capture d’écran 2020-11-21 à 21 51 52](https://user-images.githubusercontent.com/44212923/99887346-dac97980-2c43-11eb-8f5c-5500357c487e.png)

😇

I don't think that I will implement this enhancement inside "macros" / "launch command on connection" because this enhancement is more related to the terminal settings :
![Capture d’écran 2020-11-21 à 21 56 33](https://user-images.githubusercontent.com/44212923/99887411-79ee7100-2c44-11eb-94b5-775b80589784.png)

So I will add this terminal settings option :
* Start connection with
  * Shell (default)
  * Custom command

You will then be able to add any custom command, like :
* --osh info
* info
* etc...

I'm now working on the UI

**Comment by snk33** [comment]
Wow that’s awesome thanks !

Indeed my first thought was to check terminal settings to do this, it does make sense.

I hope it’ll help people to use this kind of solutions (including you ? 🙃)

**Comment by isontheline** [comment]
Yes including me 😁

I will release this beta version in a few hours :
![Capture d’écran 2020-11-23 à 08 08 14](https://user-images.githubusercontent.com/44212923/99936394-5241fa80-2d63-11eb-8cae-c2bedfe8b919.png)

**Comment by isontheline** [comment]
Now available for beta testing :
https://testflight.apple.com/join/QSrBK59z

☀️ Have a nice day

**Comment by snk33** [comment]
I've tested the beta version, it works as expected. I was able to send --osh command on login and mostly set a connection to specific server by giving a command "user@host".

Just one detail, when I want to edit the custom command I must disable it then select "Custom" again. No need to implement complicated list of command or anything, just be able to edit the command by clicking another time on "Custom" would be nice :)

**Comment by isontheline** [comment]
Thanks for your feedback @snk33!

No problem I will fix this glitch asap 😇

I will come back to you shortly.

**Comment by isontheline** [comment]
A new TestFlight release is now available

**Comment by snk33** [comment]
Tested, everything's fine now ! :)

**Comment by isontheline** [comment]
Thank you again for your feedback 👍
