### ISSUE TITLE
Old interface

### ISSUE THREAD

**Issue by twabulldogg** [isontheline/pro.webssh.net#216]
I would like the old interface to be available where I am able to use swipe guestires to clone or delete configurations.  Having the extra pop up whenever I want to perform any task, including closing a tunnel connection, is extremely frustrating.

**Comment by isontheline** [comment]
Hello @twabulldogg 👋

That's why 14.11 - Milky Way has been release a few minutes ago on the App Store.
Two possibilities to test the new behavior :

1. Wait a few hours to have the download ready on the App Store
2. Download 14.11 on TestFlight :  https://testflight.apple.com/join/QSrBK59z

Could you tell me if the new behavior is better?

☀️ Have a nice day

**Comment by twabulldogg** [comment]
Thank you!  The new interface works great.

I do have a bug now, though, in that I cannot connect to tunnels anymore.  I can SSH to the box, though.  The tunnel connection says, “the connection couldn’t be completed, NEVPNErrorDomain, Error 2.”  I have not changed the configurations since updating to the latest version.

Thank you.

________________________________

**Comment by isontheline** [comment]
1. Just go to iOS Settings > VPN > Then remove "VPN-Over-SSH"
2. Launch your tunnel again
3. Approve the installation of the VPN profile

**Comment by twabulldogg** [comment]
Works perfectly.  Thank you for all your quick responses.

________________________________

**Comment by isontheline** [comment]
You're Welcome
