### ISSUE TITLE
Import / Export Servers

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#252]
# Progress
- [x] Export to ssh_config
- [x] #792

# Request
I had WebSSH installed on my phone for a while for some reason, but just today purchased Premium and started using it.

I am looking forward to import/export (and sync), I have a lot of servers to connect to and setting them all up manually is a pain in the neck. Even from a simple text file, JSON or XML would be better than nothing. Or manually editing a database file in worst case.

(I used Termius/iTerminal for years and paid for it, but just don't like another subscription for my occasional use - I always try to get to a real computer anyway if possible)

I assume importing would be of higher priority for me personally, but either way both would be great and will drive new users towards the app. While you are at it, export would also be nice :)

I am using SecureCRT. It's a commercial application and Termius also allows imports from SecureCRT's exported XML file.

As far as I know the way to export hosts from Termius is via their CLI:

termius export-ssh-config # Export to ./termius/sshconfig

https://github.com/termius/termius-cli

Not sure what format that would be.

_Originally posted by @alexhk in https://github.com/isontheline/pro.webssh.net/issues/43#issuecomment-782680639_

**Comment by isontheline** [comment]
@alexhk How many connections are you using?

**Comment by alexhk** [comment]
Apologies for the late reply, and thanks for keeping the import function in mind.

Currently I am using only two connections, the main one a machine at the office  which I use to connect to my target systems ;) 

Once we have an import function I'll add around 10 at first, 20-25 eventually if it goes smoothly. Connecting directly is preferred, as now I have to use VPN on the mobile device and copy and paste credentials to the shell.

The easiest seems to export the connections as CSV from SecureCRT. The company provided a simple script to do just that a while ago. Otherwise there is a XML export function for settings and connections.

**Comment by isontheline** [comment]
No problem, thanks for your reply

Could you post here the CSV format including headers if any (without any credentials of course)?

I will then start the import implementation.

**Comment by alexhk** [comment]
SecureCRT does not produce a CSV by default, the CSV file is the result of a custom script which in its basic form is provided by VanDyke but needs to be modified. 

Hence, it will be different from user to user. I I suggest you define the expected fields in your app. And the export needs to be customized to fit your WebSSH requirements. 

But in any case, here is the output from my script from SecureCRT. 

**Folder = Group name**

Flattened, since SecureCRT uses real folders including sub-folders, ie. Servers/AWS/Production/DB-Server1 would become "Servers AWS Production DB-Server1" in the CSV.

**SessionName = Name**

**Hostname, Port, Username, Protocol, Emulatoin = self explanatory**

It does not include a password. I could include it, but it would be encrypted and decrypting it would probably require asking the maker of SecureCRT or doing some research on their API. In my case, I don't need it, most connections use public key auth and moving a CSV file around with an unencrypted password is probably not permissible under most client agreements.

**Authentications:**

I included the field strAuthentications, which would indicate what auth-methods are allowed on the server (could be more than one though, see example CSV).  Not sure what you could do with this info, but the script could be changed to include public key serial numbers and such from the original SecureCRT connection (INI) files, but this exceeds my own requirements.

[IterationOutputFile.zip](https://github.com/isontheline/pro.webssh.net/files/6349683/IterationOutputFile.zip)

Hope that helps.

**Comment by isontheline** [comment]
Thank you @alexhk for providing an example!

You're right I will define WebSSH' own CSV import format.

I'm increasing the priority of this issue and I will try to make it alive soon.

**Comment by isontheline** [comment]
Thank you a lot for your support @TimDowker 🙏

No progress yet 😢

How many hosts do you need to import?

**Comment by TimDowker** [comment]
Thank you for getting back to me.  I have about 60-75 different hosts setup in Termius.  Recreating them would be a P.I.T.A. (Pain In The A$$) :)

**Comment by isontheline** [comment]
@TimDowker 
You're welcome!

* Do you will use https://github.com/termius/termius-cli to export your ssh config?
* Does your hosts all use Private Key? (I ask because ssh config doesn't contain passwords.)

**Comment by TimDowker** [comment]
I've tried using termius-cli to export but unfortunately it hasn't been updated to support the new encryption of the desktop client.  No private keys.

**Comment by isontheline** [comment]
@TimDowker How will you export your connections? 

I would like to help you as much as I can.

**Comment by TimDowker** [comment]
I guess I'll have to wait for them to update their command line client before I can proceed.  Thank you for your help.

https://github.com/termius/termius-cli/issues/188

**Comment by isontheline** [comment]
> I use SecureCRT for work and would like to be able to do an import of my sessions into WebSSH from a backup of the SecureCRT sessions XML file. Is that a possibility for a feature?

From @Z1mDMan
https://github.com/isontheline/pro.webssh.net/discussions/1005

**Comment by isontheline** [comment]
WebSSH 24.3.1215 can now import ssh_config aliases from a file : https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment]
You can now export servers to a ssh_config file inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
