### ISSUE TITLE
Traceroute

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#273]
I think it would be in incredibly help to have Trace route in the tools section.

_Originally posted by @tmcb82 in https://github.com/isontheline/pro.webssh.net/discussions/271_

- [x] Changer icone de play vers stop
- [x] Afficher erreur swiftmessages
- [x] Pouvoir specifier ipv4/ipv6
- [x] Afficher latence
- [x] Pouvoir copier une IP de hop
- [x] Network tools : vibrations

**Comment by mbierman** [comment]
+1!

**Comment by isontheline** [comment]
For @isontheline work :
* http://opensource.apple.com/source/network_cmds/network_cmds-77/traceroute.tproj/

**Comment by TCB13** [comment]
+1 on this, here's a good example from the [HE Network Tools](https://apps.apple.com/app/id858241710):

![photo_2024-05-09_20-42-40](https://github.com/isontheline/pro.webssh.net/assets/6315832/aa3114b1-1bca-4c9b-b743-bc7c64bb03c1)

Their tool is capable of running IPv4 and IPv6 traceroutes for those cases when you enter a domain name instead of an IP on the input field.

**Comment by isontheline** [comment]
Thank you @TCB13 👍

Traceroute implementation is not trivial but I bring up this issue in order to plan the roadmap

**Comment by TCB13** [comment]
> Thank you @TCB13 👍
> 
> Traceroute implementation is not trivial but I bring up this issue in order to plan the roadmap

Yes, I'm well aware of that, I just wanted to share the HE screenshot as their app is really quite nice.

**Comment by isontheline** [comment]
I agree, nice and clear design

I hope I will be able to implement it "soon"

**Comment by isontheline** [comment]
A "simple" traceroute is now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
