### ISSUE TITLE
WebSSH essential not working on IOS 14.6

### ISSUE THREAD

**Issue by rgonomike** [isontheline/pro.webssh.net#316]
Hi,

Is WebSSH Essential going to be updated on IOS 14.6 please?
It's not working anymore and in case it's not, how can I recover my saved servers from there? Really need it...

Thanks

**Comment by isontheline** [comment]
Hi @rgonomike Bastien 👋

WebSSH Essential is unsupported since several years.
Unfortunately I have no way to recover your saved servers as the database can't be exported from this older release.

Contact me in private if you want to exchange your old invoice with a WebSSH Pro : https://webssh.net/documentation/legal/company-behind-webssh/

Have a nice day ☀️
