### ISSUE TITLE
WebSSH on Intel CPU

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#322]
- [x] Doesn't work : [NSProcessInfo processInfo].isiOSAppOnMac
  * Bad behavior : Go to fullscreen on macOS instead of windowed
- [x] Doesn't work : RMAppReceipt* receipt = [RMAppReceipt bundleReceipt];
  * Can't check receipt anymore

**Comment by jarrah31** [comment]
Thank you Arnaud for adding this as a future enhancement from my review comment, it will be truly amazing to have a single, iCloud synchronised application to manage my SSH clients between MacOS, iPhone, and iPad. I've been using iTerm2 and .ssh/config for years due to there being no decent alternatives aimed at the hobbyist market who don't want to pay silly money for a monthly subscription (I'm looking at you Termius). 

Having the ability to configure all my ssh clients (lots of Raspberry Pi's, a couple of Docker servers, and some family IT) in a single app that is available on Mac, iPad, and iPhone, at a price that is just right, really makes your app stand out above all the others! I will certainly be letting all my Intel Mac owning friends know about this when available. :) 

The other thing that makes your app stand out is your customer engagement! Responding to app reviews, listening to and implementing feedback, the ability to interact with you on Github, it's all positive stuff! 

The future Proxy Jump feature just makes this even more better too! I have one more idea/feature request that I'll submit later today. :)

**Comment by isontheline** [comment]
> Thank you Arnaud for adding this as a future enhancement from my review comment

You're Welcome 👍 

> , it will be truly amazing to have a single, iCloud synchronised application to manage my SSH clients between MacOS, iPhone, and iPad. 

Yes I was also looking for a such product and I decided to make it alive because I need it for home and office uses.

> I've been using iTerm2 and .ssh/config for years due to there being no decent alternatives aimed at the hobbyist market who don't want to pay silly money for a monthly subscription (I'm looking at you Termius).

Termius is a great (perhaps the best) SSH client but, you're right the monthly subscription is a no go for me.

> Having the ability to configure all my ssh clients (lots of Raspberry Pi's, a couple of Docker servers, and some family IT) in a single app that is available on Mac, iPad, and iPhone, at a price that is just right, really makes your app stand out above all the others!

Thank you so much for your support @jarrah31 ❗️❤️❗️

> I will certainly be letting all my Intel Mac owning friends know about this when available. :)

Thank you very much 😇

> The other thing that makes your app stand out is your customer engagement! 

I try to do my best to respond to every customer in a manner that everyone will be happy

> Responding to app reviews, listening to and implementing feedback, the ability to interact with you on Github, it's all positive stuff!

Thank you so much @jarrah31 🙏

> The future Proxy Jump feature just makes this even more better too! 

I need it a lot because VPN doesn't fit all my needs

> I have one more idea/feature request that I'll submit later today. :)

Of course you can 😉

Have a nice day ☀️

**Comment by isontheline** [comment]
Always waiting for a few third party libraries to be updated for x68_64 🕙

**Comment by isontheline** [comment]
@jarrah31 
WebSSH 16.0 - Gem has been submitted to Apple for verification. 
It should supports Intel arch 🤞

**Comment by isontheline** [comment]
There was a crash during the review 😢
I'm fixing the issue.

**Comment by Ghareeb26** [comment]
ls

**Comment by Ghareeb26** [comment]
@Ghareeb26

**Comment by isontheline** [comment]
WebSSH is now available on macOS since 16.0
Please open an issue for any glitches.

Have a nice day ☀️

**Comment by jarrah31** [comment]
I missed all my email notifications for this so apologies for the late reply.
This is really great news, I'm going to try this out now, thank you very much for implementing this new feature!

**Comment by jarrah31** [comment]
It really is great to finally have a decent MacOS SSH solution that syncs connections between iDevices without having to pay through the nose for the privilege. Thank you Arnaud!

Only issue I've seen so far is the pop-up notification bar was partially hidden when it notified I needed a pro subscription and when I restored my purchase.

**Comment by isontheline** [comment]
Thank you a lot @jarrah31 for your feedback and support about WebSSH 🙏

**Comment by jarrah31** [comment]
@isontheline  I've noticed that there's no information in the app description about the ability to sync saved profiles between iPhone, iPad, and macOS, or the fact that macOS is supported too. This is an important feature for me and is something I would be looking for in the app description, so would it be possible to add this please to help future users?
