### ISSUE TITLE
mashREPL : Standard Input Implementation

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#334]
The following should work:
```
> nslookup
> set querytype=soa
> stackoverflow.com
Server:         217.30.180.230
Address:        217.30.180.230#53
```

 But nothing works after `nslookup`.

**Comment by isontheline** [comment]
Hello @mbierman 👋

Thanks for your issue.

I have updating the [documentation](https://webssh.net/documentation/mashREPL/) :
![image](https://user-images.githubusercontent.com/44212923/124396580-b28e1700-dd0a-11eb-927a-f59c7b37088b.png)

Yet mashREPL commands don't support standard input so commands can't be interactive.

I'm changing this issue title in order to implement standard input on all commands.
