### ISSUE TITLE
missing ed25519 support

### ISSUE THREAD

**Issue by michaaa** [isontheline/pro.webssh.net#54]
WebSSH doesn’t support ed25519 keys right now, this makes some servers unreachable for public key authentication. Is it possible to add support for ed25519 private keys?

**Comment by isontheline** [comment]
Hello @michaaa 

Thanks for your issue!

ed25519 support should be available since #5

I'm closing this issue because it have a lake of:
- evidences that WebSSH doesn't support ed25519 (any logs?)
- bug model report (https://github.com/isontheline/pro.webssh.net/issues/new?assignees=&labels=&template=bug_report.md&title=) is missing, which device?, which iOS version?, which ssh server version? which linux distribution?

Please provide us all logs on both sides in order to reopen this issue :
- error displayed on WebSSH side
- error displayed on SSH side

☀️ Have a nice day

**Comment by isontheline** [comment]
Could you also put informations about your public key :
ssh-keygen -l -f /private/etc/ssh/ssh_host_ed25519_key.pub
