### ISSUE TITLE
SFTP : Better support of symlinks

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#547]
**Describe the feature**
Symlinks are yet displayed as "simple file". Improve WebSSH in order to better support them.

**Comment by isontheline** [comment]
Now three strategies are implemented :
* None : don't show symlinks
* Lazy : show symlinks but don't check the target link. Some context actions could be available.
* Eager : show symlinks and request server for additional data about them (target path, is it a file or directory?)

**Comment by drmrbrewer** [comment]
@isontheline is there an option for this in the settings?  i.e. to use the "eager" strategy?  The symlinks in my remote host are not showing up properly, i.e. a folder symlink doesn't act as a folder and a file symlink doesn't act as a file (and show details of the linked file).

**Comment by isontheline** [comment]
@drmrbrewer New settings have been moved to iOS > Settings > WebSSH

Could you make a try?

**Comment by drmrbrewer** [comment]
@isontheline ah, yes... I'm relatively new to iOS and forgot the confusing situation where some apps have all their settings in the app itself, others have all their settings in the system settings, and others have a mixture.  Out of interest, why are some settings remaining in the app, and not in the system settings?  I understand that some settings you might want to protect behind Face ID, but the settings in `App > WebSSH Settings` seem to be the type of setting that fits in the system settings?

Regarding the "eager" strategy for symlinks, it works mostly as I expect, thanks!  I have a couple of comments:

Perhaps "eager" should be the default?  What is the downside of "eager" vs "lazy"?

For symlinked files, in the file listing I would personally like to see the size of the linked file (e.g. `1.11 GB`), not of the link itself (e.g. `42 B`), i.e. to make it appear more like it is an actual file (i.e. if you open it, you will open the `1.11 GB` file, not the `42 B` symlink).  And use a different icon to make it more clear that the file is a symlink to a file, not the file itself.  This is partly because in one of my folders the filenames are very long, so I can't see the symlink arrow icon in the file name unless I turn the screen to landscape (and I wouldn't normally want to do that).

**Comment by isontheline** [comment]
@drmrbrewer 

> why are some settings remaining in the app, and not in the system settings?

Lack of time : https://github.com/isontheline/pro.webssh.net/issues/38

> Perhaps "eager" should be the default?

It could but it's a relative new feature so I need more feedback from users.

> What is the downside of "eager" vs "lazy"?

It involves more requests from WebSSH to the SFTP server so it could slow down the connection if you are on slow link.

> EDIT... I've added these suggestions https://github.com/isontheline/pro.webssh.net/discussions/819.

Thank you so much @drmrbrewer 🙏
