### ISSUE TITLE
Opening a server generates two sessions (macOS)

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#617]
# Bug description
When I open an SSH session in WebSSH 18.0 beta (build 901), it opens up two sessions to the same SSH server within the same tab. 

# Screenshots
<img width="740" alt="image" src="https://user-images.githubusercontent.com/3072303/168484091-e92f981a-31a9-407e-bc6e-9fe2c12cf072.png">

# Steps to reproduce
1. Double click an SSH session
2. Two session open up at the same time
3. Have to eject/close down both sessions to reveal the server list

**Comment by isontheline** [comment]
Good catch @jarrah31 !

Does the double click is a real daily use?
I think the problem was already there but « not visible ».

I’m fixing it anyway

**Comment by jarrah31** [comment]
Apologies, it just dawned on me that it's my double-clicking that causes two sessions to appear! I hadn't realised what I was doing - double clicking seemed a natural way to open an ssh session in that moment. I'm now not sure if I was double or single clicking on previous versions... :) 
So I guess the fix will be to just open a single session even if double clicking? That works for me. :) 

btw, I really like having the bookmark bar (is that the right name for it?) appear on the left hand side - it feels like a more logical way of displaying sessions and navigating WebSSH.
Are there any plans to use a similar bookmark bar on the iPad version to mimic the way safari works on there too?

Also, would it be worth listing saved connections in the left-hand bookmark bar, within Inventory -> SSH (as well as SFTP and Tunnels), that is then organised by the same folder structure that can be expanded and closed? 
e.g. if I open a new tab, all my servers are listed in the pain window. It would be useful if that same list of folders and servers were shown in the left-hand bookmarks bar as well.
It feels like a natural place to list saved Connections as there's a lot of available space there. Perhaps the layout and navigation could mimic Safari's bookmarks bar? Maybe even use the same type of icons for showing the tab overview, etc... 

Got carried away with myself there - seeing the bookmarks bar in the new version made me think of how Safari works. I don't mind if not though, I just wanted to share my thoughts on that. :)

**Comment by isontheline** [comment]
> Apologies, it just dawned on me that it's my double-clicking that causes two sessions to appear! I hadn't realised what I was doing - double clicking seemed a natural way to open an ssh session in that moment. I'm now not sure if I was double or single clicking on previous versions... :) So I guess the fix will be to just open a single session even if double clicking? That works for me. :)

Yes I'm fixing the double click trouble so double click will only result to open only one connection 😉

> btw, I really like having the bookmark bar (is that the right name for it?) appear on the left hand side - it feels like a more logical way of displaying sessions and navigating WebSSH. Are there any plans to use a similar bookmark bar on the iPad version to mimic the way safari works on there too?

Apple call it the "sidebar" and in some apps you're right that's the bookmark bar one. On Safari there are bookmarks and also grouped tabs.

Yes I'm also planning to add the sidebar on iOS (iPad and iPhone) but I need to have more feedback like yours on this new implementation on macOS. I have tried to implemented it in the last 60 days and I was wondering if it will be or not a great enhancement for WebSSH' users.

> Also, would it be worth listing saved connections in the left-hand bookmark bar, within Inventory -> SSH (as well as SFTP and Tunnels), that is then organised by the same folder structure that can be expanded and closed? e.g. if I open a new tab, all my servers are listed in the main window. It would be useful if that same list of folders and servers were shown in the left-hand bookmarks bar as well. It feels like a natural place to list saved Connections as there's a lot of available space there. Perhaps the layout and navigation could mimic Safari's bookmarks bar? Maybe even use the same type of icons for showing the tab overview, etc...

That's sound great! 

My first attempt have used expanded entries like this screenshot :
<img width="173" alt="image" src="https://user-images.githubusercontent.com/44212923/168490620-501edd94-3e8c-40c8-87f3-9173d8ff92bc.png">

I have reverted back to an easier implementation because (as sais before) I would like users' feedback to drive my work.

Could you open an issue with all your wishes? It will help me a lot 🙏

> Got carried away with myself there - seeing the bookmarks bar in the new version made me think of how Safari works. I don't mind if not though, I just wanted to share my thoughts on that. :)

The sidebar is now used by a lot of apps and WebSSH will use it as much as it can help users in their daily works.

I love your feedbacks and discussions, thank you again @jarrah31

**Comment by isontheline** [comment]
Now available inside WebSSH 18.0 RC2 (macOS)

Have a nice day ☀️
