### ISSUE TITLE
After switching to a new Iphone I cannot download the license

### ISSUE THREAD

**Issue by blobf75** [isontheline/pro.webssh.net#63]
Yesterday I moved data to the new Iphone. WebSSH has been automatically installed but I cannot download my free license. I used the free version on 1st September 2020. What can I do?

**Comment by isontheline** [comment]
Hello @blobf75 

WebSSH contains In-App Purchases since August 29, 2020 (and it's free since).
So since August 29, 2020 you need to purchase the "Unlimited" feature inside WebSSH in order to add unlimited connections.

As the migration may have been broken for any reason in your case, please contact me here :
https://mengus.net/#contact

☀️ Have a nice day
