### ISSUE TITLE
WHOIS Rendering Improvement

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#733]
# Feature description
It’s just not practical to just split after every colon <:>.

![image](https://user-images.githubusercontent.com/44212923/189988263-0598bfab-5750-42b9-8177-09d973d89773.png)

From **Anonymous** on *TestFlight*

**Comment by TCB13** [comment]
@isontheline I've a suggestion but I'm not sure you're going to like it! The current whois tool is mostly useless and why not simplify it and make it work like others? I mean **simply display selectable text instead of trying to parse it**.

Here's an example from the [HE Network Tools](https://apps.apple.com/app/id858241710) App:

![IMG_736975829881](https://github.com/isontheline/pro.webssh.net/assets/6315832/550ce356-270b-4259-a0a9-9cc2598c9d68)

This makes way more sense and is way more useful than the current implementation that doesn't allow copy and doesn't work properly on phones.

**Comment by isontheline** [comment]
I like your suggestion @TCB13 👍 😉

I will so make this enhancement!

**Comment by TCB13** [comment]
> I like your suggestion @TCB13 👍 😉
> 
> I will so make this enhancement!

Great, this is probably way easier to do than having to parse things and fit them into a list view.

**Comment by isontheline** [comment]
Now available inside the latest beta release : https://testflight.apple.com/join/QSrBK59z
