### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by k4k4rot0** [isontheline/pro.webssh.net#808]
# Adicionar FTP
_Olá, boa noite! Tudo bem? Espero que sim! Sou usuário Premium do WebSSH, e gostaria de solicitar, se possível, que o WebSSH tivesse FTP. ^_^

**Comment by isontheline** [comment]
Olá @k4k4rot0 👋

Thank you so much for your purchase and your support about WebSSH 🙏

FTP support is already tracked here : https://github.com/isontheline/pro.webssh.net/issues/315
I'm merging this issue with this one.

Yet I don't have implemented FTP.
I need to share a poll in order to let users vote on this feature more than others.

Have a nice day ☀️

**Comment by k4k4rot0** [comment]
Certo, muito obrigado! Espero que o FTP de certo! =D
