### ISSUE TITLE
Unable to SSH to a AWS host with SSH key but not password set

### ISSUE THREAD

**Issue by miroslavkovac** [isontheline/pro.webssh.net#860]
# Bug description
I typically ssh to an AWS machine like this:

```
ssh -i ~/.ssh/key.pem ubuntu@mydomain.com
```

Not that there is no password set on this instance. The above command works perfectly on macOS.

I tried to replicate the same setup with the app:
1. Creating a new connection
2. Linking SSH key
3. Configuring username
4. **Leaving password field empty**
5. I try to connect I get a prompt to enter password
6. I leave password input empty and click Connect 
7. Nothing happens (no error, no connection)

I suspect this is related to no password but I can be wrong. In any case it would be worth showing any kind of an error from the app in order to help with debugging the issue.

**Comment by isontheline** [comment]
Hello @miroslavkovac 👋

Thank you so much for your issue 🙏

Could you enable versboe logging please in order to find the root cause?

# macOS
In order to enable verbose logging you can follow the steps :
1. Launch WebSSH
2. WebSSH menu (top bar)
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Launch mashREPL (inside WebSSH)
8. Type `pwd`
9. Go to the folder printed
10. Find WebSSH logs there

# iOS
In order to enable verbose logging you can follow the steps :
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

**Comment by isontheline** [comment]
You're Welcome !

Thank you a lot for your quick and strong feedback 🙏
