### ISSUE TITLE
ssh with private key not work

### ISSUE THREAD

**Issue by leechoohyoung** [isontheline/pro.webssh.net#944]
# Bug description
_Put here a clear and concise description of what the bug is_
I set up my private key (pem file) for authentication to ssh, but password input popup show up.

# Screenshots
_If applicable, add screenshots to help explain your problem_
<img width="764" alt="스크린샷 2023-07-27 18 18 26" src="https://github.com/isontheline/pro.webssh.net/assets/4285647/a6e7f19d-8e19-419f-b352-c457ff09bf31">

<img width="508" alt="스크린샷 2023-07-27 18 20 16" src="https://github.com/isontheline/pro.webssh.net/assets/4285647/886a1d34-9bb8-4bd6-b153-8b86dc5cc1c5">

# Steps to reproduce
1.  create connection
2. set private key (pem file)
3.  try connect
4. Error is thrown

**Comment by isontheline** [comment]
Thanks for your feedback @leechoohyoung 🙏

Please try to extract the root cause : 
1. iOS Settings
2. WebSSH
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Find the log files inside iOS > Files > WebSSH

It could be also a problem on the key itself : WebSSH doesn't accept too weak keys.
If so please generate a new one inside WebSSH itself.

I'm here if you need any further help.

Have a nice day ☀️

**Comment by leechoohyoung** [comment]
well, first of all, 
I`m using WebSSH in m1 MacBook pro.
And already set log level to verbose, but I don't know where to find a log file.
Finally, I believe key file is fine because it is generated in amazon ec2 console and when I use key file in terminal via ssh command it works.

any help?

**Comment by isontheline** [comment]
In order to enable verbose logging on macOS you can follow the steps :
1. Launch WebSSH
2. WebSSH menu (top bar)
3. Settings
4. Log Level > Verbose
5. Restart WebSSH
6. Reproduce your action
7. Launch mashREPL (inside WebSSH)
8. Type `pwd`
9. Go to the folder printed
10. Find WebSSH logs there

> Finally, I believe key file is fine because it is generated in amazon ec2 console and when I use key file in terminal via ssh command it works.

It can works on other softwares but not on WebSSH as some algorithms have been deprecated on it.

**Comment by leechoohyoung** [comment]
OK, I found log files. 
Plz check the log files.
Thx.
[log-20230727.txt](https://github.com/isontheline/pro.webssh.net/files/12183274/log-20230727.txt)

**Comment by isontheline** [comment]
Thanks for the logs @leechoohyoung 

This error could happen when the Private Key use a deprecated algorithm.

Please try to generate a new PKey from inside WebSSH and export the public key to your EC2 Instance.

**Comment by leechoohyoung** [comment]
OK, I`ll try. And I close this issue for now.
Thx.

**Comment by leechoohyoung** [comment]
one more thing, How I can generate a new key inside WebSSH?

**Comment by isontheline** [comment]
@leechoohyoung Go to WebSSH Settings > Keys > Use the top right button on the navigation bar 

Could you see it?

**Comment by leechoohyoung** [comment]
yes, thx. really. :)

**Comment by isontheline** [comment]
You're welcome
